# Generated by Django 5.2.3 on 2026-01-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('nutritionist', 'Nutritionist'), ('admin', 'Admin'), ('regulator', 'Regulator')], default='regular', max_length=20),
        ),
    ]
